# Generated by Django 5.0.6 on 2024-10-20 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_info', '0002_doctorinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.doctorinfo')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.patientinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PatientStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(max_length=50)),
                ('heart_rate', models.IntegerField()),
                ('other_notes', models.TextField()),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attending.attendancerequest')),
            ],
        ),
    ]
