# Generated by Django 5.0.6 on 2024-10-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientstats',
            name='other_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
